"""Add password hash to users

Revision ID: 022308c216ae
Revises: d96445bb8bff
Create Date: 2026-08-20 13:23:51.740932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '022308c216ae'
down_revision = 'd96445bb8bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_assignment')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    op.create_table('task_assignment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('maintenance_request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('assignment_method', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_request.id'], name=op.f('task_assignment_maintenance_request_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('task_assignment_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_assignment_pkey'))
    )
    # ### end Alembic commands ###
