"""add property to maintenance requests

Revision ID: 043dd9ae7bfb
Revises: eca8ceba08f8
Create Date: 2026-10-04 13:33:56.507373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043dd9ae7bfb'
down_revision = 'eca8ceba08f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'property', ['property_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('property_id')

    # ### end Alembic commands ###
