"""add external worker messages

Revision ID: 04c17a36bda2
Revises: ee08e6ab519d
Create Date: 2026-09-26 21:40:21.364010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c17a36bda2'
down_revision = 'ee08e6ab519d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_worker_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_request_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('resend_message_id', sa.String(length=255), nullable=True),
    sa.Column('in_reply_to', sa.String(length=255), nullable=True),
    sa.Column('message_id', sa.String(length=500), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['external_worker_candidate.id'], ),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_worker_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_worker_message_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_worker_message_in_reply_to'), ['in_reply_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_worker_message_maintenance_request_id'), ['maintenance_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_worker_message_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_worker_message_resend_message_id'), ['resend_message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_worker_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_worker_message_resend_message_id'))
        batch_op.drop_index(batch_op.f('ix_external_worker_message_message_id'))
        batch_op.drop_index(batch_op.f('ix_external_worker_message_maintenance_request_id'))
        batch_op.drop_index(batch_op.f('ix_external_worker_message_in_reply_to'))
        batch_op.drop_index(batch_op.f('ix_external_worker_message_candidate_id'))

    op.drop_table('external_worker_message')
    # ### end Alembic commands ###
