"""Create task assignment table

Revision ID: 2f4c735fa989
Revises: 022308c216ae
Create Date: 2026-08-21 17:27:25.809235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4c735fa989'
down_revision = '022308c216ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assignment_method', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.CheckConstraint("assignment_method IN ('manual', 'ai')", name='check_assignment_method'),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 1)', name='check_assignment_score'),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assignment_maintenance_request_id'), ['maintenance_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_assignment_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_assignment_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_assignment_maintenance_request_id'))

    op.drop_table('task_assignment')
    # ### end Alembic commands ###
