"""add ranking updated timestamp

Revision ID: 3a4fd3aefc43
Revises: c2b7e1d7a421
Create Date: 2026-08-27 21:55:00.203580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4fd3aefc43'
down_revision = 'c2b7e1d7a421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_worker_candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranking_updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('external_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('availability',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_external_worker_candidate_contact_status'), ['contact_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_worker_candidate_is_selected'), ['is_selected'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_worker_candidate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_worker_candidate_is_selected'))
        batch_op.drop_index(batch_op.f('ix_external_worker_candidate_contact_status'))
        batch_op.alter_column('availability',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('external_id',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('ranking_updated_at')

    # ### end Alembic commands ###
