"""Add Gemini contractor workflow fields

Revision ID: 4b3041f333e3
Revises: ea6272d70e97
Create Date: 2026-08-27 00:46:35.960515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3041f333e3'
down_revision = 'ea6272d70e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'external_worker_candidate',
        schema=None
    ) as batch_op:

        batch_op.add_column(
            sa.Column(
                'website',
                sa.String(length=500),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'phone',
                sa.String(length=50),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'email',
                sa.String(length=255),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'source_url',
                sa.String(length=500),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'match_score',
                sa.Float(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'match_reason',
                sa.Text(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'contact_status',
                sa.String(length=50),
                nullable=False,
                server_default='discovered'
            )
        )

        batch_op.add_column(
            sa.Column(
                'email_sent_at',
                sa.DateTime(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'response_received_at',
                sa.DateTime(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'last_message',
                sa.Text(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'gemini_summary',
                sa.Text(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'quoted_price',
                sa.Float(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'estimated_start',
                sa.String(length=100),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'updated_at',
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.now()
            )
        )

        batch_op.alter_column(
            'availability',
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=100),
            existing_nullable=True
        )

        batch_op.alter_column(
            'contact_status',
            server_default=None
        )

        batch_op.alter_column(
            'updated_at',
            server_default=None
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'external_worker_candidate',
        schema=None
    ) as batch_op:

        batch_op.alter_column(
            'availability',
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=50),
            existing_nullable=True
        )

        batch_op.drop_column('updated_at')
        batch_op.drop_column('estimated_start')
        batch_op.drop_column('quoted_price')
        batch_op.drop_column('gemini_summary')
        batch_op.drop_column('last_message')
        batch_op.drop_column('response_received_at')
        batch_op.drop_column('email_sent_at')
        batch_op.drop_column('contact_status')
        batch_op.drop_column('match_reason')
        batch_op.drop_column('match_score')
        batch_op.drop_column('source_url')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('website')

    # ### end Alembic commands ###