"""add external worker candidates

Revision ID: 655d8ea4eed0
Revises: 8fd6075867c2
Create Date: 2026-08-24 21:24:44.569662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655d8ea4eed0'
down_revision = '8fd6075867c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_worker_candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_request_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('trade', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_worker_candidate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_worker_candidate_maintenance_request_id'), ['maintenance_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_worker_candidate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_worker_candidate_maintenance_request_id'))

    op.drop_table('external_worker_candidate')
    # ### end Alembic commands ###
