"""add contractor response quality

Revision ID: c2b7e1d7a421
Revises: 4b3041f333e3
Create Date: 2026-08-27 15:40:39.718329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b7e1d7a421'
down_revision = '4b3041f333e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_worker_candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_quality', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_worker_candidate', schema=None) as batch_op:
        batch_op.drop_column('response_quality')

    # ### end Alembic commands ###
