"""Clean up external worker candidate fields

Revision ID: ee08e6ab519d
Revises: 3a4fd3aefc43
Create Date: 2026-08-30 22:06:54.175641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee08e6ab519d'
down_revision = '3a4fd3aefc43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_worker_candidate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_worker_candidate_contact_status'))
        batch_op.drop_column('estimated_start')
        batch_op.drop_column('gemini_summary')
        batch_op.drop_column('quoted_price')
        batch_op.drop_column('response_quality')
        batch_op.drop_column('contact_status')
        batch_op.drop_column('last_message')
        batch_op.drop_column('response_received_at')
        batch_op.drop_column('email_sent_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_worker_candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('response_received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_message', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('contact_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('response_quality', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quoted_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gemini_summary', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estimated_start', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_external_worker_candidate_contact_status'), ['contact_status'], unique=False)

    # ### end Alembic commands ###
